version: "2"
services:
  inked:
    build: .
    image: capgemini-invent-ide/inked
    container_name: inked
    ports:
      - 5552:5552
    volumes:
      - .:/opt/working
    entrypoint: inked-demo
    environment:
      - INKED_HOST=http://localhost:5552
  mkdocs-inked:
    build: ./docs
    image: capgemini-invent-ide/inked-mkdocs
    container_name: inked-mkdocs
    ports:
      - "8000:8000"
    volumes:
      - .:/docs